### ISSUE TITLE
AUR package does not work

### ISSUE THREAD

**Issue by andremarcais** [vmavromatis/absolutely-proprietary#38]
I installed the AUR package for Absolutely Proprietary. Running ``absolutely-proprietary`` gives:
```
Traceback (most recent call last):
  File "/usr/bin/absolutely-proprietary", line 9, in <module>
    for entry_point in distribution('absolutely-proprietary==1.0.0').entry_points:
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: absolutely-proprietary==1.0.0

```

**Comment by DikeKike** [comment]
I get a similar error, as described in #41

**Comment by zefr0x** [comment]
This should be reported to the AUR package it self, not the source.
