### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sisyphus74** [vmavromatis/absolutely-proprietary#41]
I have an error running $ python absolutely_proprietary/__init__.py:
`Retrieving local packages (including AUR)...
Downloading https://git.parabola.nu/blacklist.git/plain/blacklist.txt
Downloading https://git.parabola.nu/blacklist.git/plain/aur-blacklist.txt
Comparing local packages to remote...
Traceback (most recent call last):
  File "/home/arthur/Downloads/absolutely-proprietary/absolutely_proprietary/__init__.py", line 126, in <module>
    reason = ((line.split(':')[4]).split(']')[0]).strip().replace('[', '')
IndexError: list index out of range
`

**Comment by DikeKike** [comment]
```
Retrieving local packages (including AUR)...
Downloading https://git.parabola.nu/blacklist.git/plain/blacklist.txt
Downloading https://git.parabola.nu/blacklist.git/plain/aur-blacklist.txt
Comparing local packages to remote...
Traceback (most recent call last):
  File "/usr/bin/absolutely-proprietary", line 33, in <module>
    sys.exit(load_entry_point('absolutely-proprietary==1.0.0', 'console_scripts', 'absolutely-proprietary')())
  File "/usr/bin/absolutely-proprietary", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/absolutely_proprietary/__init__.py", line 126, in <module>
    reason = ((line.split(':')[4]).split(']')[0]).strip().replace('[', '')
IndexError: list index out of range
```
I'm using parabola and installed it from the AUR, the same error also occurs on another machine running artix (both use openRC).
